//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrTech.Amal.SQLModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ad
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public Nullable<int> AdTypeID { get; set; }
        public Nullable<int> AreaID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string FileName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CityID { get; set; }
    
        public virtual AdType AdType { get; set; }
        public virtual AdType AdType1 { get; set; }
        public virtual Area Area { get; set; }
        public virtual Area Area1 { get; set; }
    }
}
