//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrTech.Amal.SQLModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Business
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Business()
        {
            this.BusinessGP_Log = new HashSet<BusinessGP_Log>();
            this.Employments = new HashSet<Employment>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public Nullable<int> GreenPoints { get; set; }
        public string Level { get; set; }
        public Nullable<int> EmployeeGreenPoints { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string FileName { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public string Email { get; set; }
        public Nullable<int> CityID { get; set; }
        public string OfficeName { get; set; }
        public string ContactPerson { get; set; }
        public Nullable<int> BusTypeID { get; set; }
        public Nullable<bool> IsMainBranch { get; set; }
        public string DocumentFileName { get; set; }
    
        public virtual LookupType LookupType { get; set; }
        public virtual RegBusiness RegBusiness { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BusinessGP_Log> BusinessGP_Log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employment> Employments { get; set; }
    }
}
