//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrTech.Amal.SQLModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuyBin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BuyBin()
        {
            this.BuyBinComments = new HashSet<BuyBinComment>();
        }
    
        public int ID { get; set; }
        public int BinID { get; set; }
        public int StatusID { get; set; }
        public int UserID { get; set; }
        public int Qty { get; set; }
        public string TrackingNumber { get; set; }
        public string FileName { get; set; }
        public decimal Price { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> GreenPoints { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<int> UserPaymentID { get; set; }
    
        public virtual BinDetail BinDetail { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuyBinComment> BuyBinComments { get; set; }
        public virtual UserPayment UserPayment { get; set; }
    }
}
