//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrTech.Amal.SQLModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTracking
    {
        public int ID { get; set; }
        public int RsID { get; set; }
        public string Type { get; set; }
        public Nullable<int> AssignTo { get; set; }
        public int StatusID { get; set; }
        public Nullable<int> DeliveredTo { get; set; }
        public Nullable<int> CollectedFrom { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string FileNameTakenByDriver { get; set; }
        public string FileNameTakenByUser { get; set; }
        public string FileNameTakenByOrg { get; set; }
        public Nullable<bool> CollectedPendingConfirmation { get; set; }
        public Nullable<bool> DeliveredPendingConfirmation { get; set; }
        public Nullable<System.DateTime> CollectedDate { get; set; }
        public Nullable<System.DateTime> DeliveredDate { get; set; }
    
        public virtual Status Status { get; set; }
    }
}
