//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrTech.Amal.SQLModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrgnizationGP_Log
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int GreenPoints { get; set; }
        public int OrgID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> RsID { get; set; }
        public string Type { get; set; }
        public Nullable<int> MemberID { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual User User { get; set; }
    }
}
