//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrTech.Amal.SQLModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecycleSubItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RecycleSubItem()
        {
            this.RecycleSubItemsTypes = new HashSet<RecycleSubItemsType>();
        }
    
        public int ID { get; set; }
        public int RecycleID { get; set; }
        public string Description { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsParent { get; set; }
        public Nullable<int> GreenPoints { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<int> WasteTypeID { get; set; }
    
        public virtual WasteType WasteType { get; set; }
        public virtual Recycle Recycle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecycleSubItemsType> RecycleSubItemsTypes { get; set; }
    }
}
