//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrTech.Amal.SQLModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecycleSubItemsType
    {
        public int ID { get; set; }
        public Nullable<int> RecycleSubItemID { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<int> WasteTypeID { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual RecycleSubItem RecycleSubItem { get; set; }
        public virtual WasteType WasteType { get; set; }
    }
}
