//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrTech.Amal.SQLModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Regift
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Regift()
        {
            this.RegiftComments = new HashSet<RegiftComment>();
            this.RegiftSubItems = new HashSet<RegiftSubItem>();
        }
    
        public int ID { get; set; }
        public decimal Longitude { get; set; }
        public decimal Latitude { get; set; }
        public string FileName { get; set; }
        public string RecieptFileName { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> PickupDate { get; set; }
        public int DonateToID { get; set; }
        public int StatusID { get; set; }
        public Nullable<int> CityID { get; set; }
        public int AgeGroupID { get; set; }
        public int GreenPoints { get; set; }
        public Nullable<int> NeedTypeID { get; set; }
        public string SubTypeTitle { get; set; }
        public int UserID { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Quality { get; set; }
    
        public virtual LookupType LookupType { get; set; }
        public virtual Regift Regift1 { get; set; }
        public virtual Regift Regift2 { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegiftComment> RegiftComments { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegiftSubItem> RegiftSubItems { get; set; }
    }
}
